import { ArrowUpRight, ArrowDown, Download, Code2, Database, BrainCircuit, GraduationCap } from 'lucide-react';

const projects = [
 { n: '01', type: 'FULL-STACK · CLOUD', title: 'eCommerce platform', description: 'A secure shopping platform built around reliable APIs, fast product discovery, and a hybrid cloud deployment.', points: ['Role-based access and JWT authentication', 'Product pagination, sorting, and optimized queries', 'AWS deployment with Azure hybrid cloud functionality'], tags: ['Java', 'Spring Boot', 'PostgreSQL', 'AWS'], icon: Code2 },
 { n: '02', type: 'MACHINE LEARNING · DATA', title: 'Predicting customer churn', description: 'A deep learning system that turns large-scale customer data into actionable churn predictions.', points: ['92% prediction accuracy with TensorFlow and Keras', '10M+ records processed using Spark and Hadoop', 'Automated CI/CD reduced deployment time by 40%'], tags: ['Python', 'TensorFlow', 'Spark', 'SageMaker'], icon: BrainCircuit },
 { n: '03', type: 'WEB DEVELOPMENT', title: 'Automobile management', description: 'A university project bringing automobile management workflows into a responsive web application.', points: ['Application development with Django and Flask', 'Dynamic MySQL schema for efficient data handling', 'Responsive interfaces with interactive elements'], tags: ['Python', 'Django', 'Flask', 'MySQL'], icon: Database },
];
const skills = [
 ['Languages', 'Java', 'Python', 'JavaScript', 'C++', 'SQL'],
 ['Application development', 'Spring Boot', 'Spring MVC', 'Hibernate / JPA', 'React', 'REST APIs', 'Apache Kafka'],
 ['Cloud & DevOps', 'AWS', 'Azure', 'Docker', 'Kubernetes', 'Terraform', 'Jenkins', 'Ansible'],
 ['AI & quality', 'TensorFlow', 'PyTorch', 'Scikit-learn', 'LLMs / GenAI', 'Postman', 'Selenium', 'JMeter'],
];
export default function Home() {
 return <>
  <a className="skip" href="#main">Skip to content</a>
  <header className="header"><a className="wordmark" href="#home" aria-label="Raditya Madina home">rm<span>.</span></a><nav aria-label="Main navigation"><a href="#projects">Work</a><a href="#experience">Experience</a><a href="#about">About</a></nav><a className="nav-contact" href="mailto:raditya216@gmail.com">Let’s talk <ArrowUpRight size={16}/></a></header>
  <main id="main">
   <section className="hero wrap" id="home">
    <div className="eyebrow"><span className="status-dot"/> SOFTWARE ENGINEERING · CLOUD · AI</div>
    <div className="hero-grid"><div><p className="intro">Hi, I’m Raditya.</p><h1>Thoughtful code.<br/><span>Real-world impact.</span></h1><p className="hero-copy">I’m Madina Jyothi Raditya Reddy, a software engineer building secure web applications, scalable cloud systems, and intelligent experiences.</p><div className="actions"><a className="button primary" href="#projects">Explore my work <ArrowDown size={17}/></a><a className="button secondary" href="/raditya-madina-resume.pdf" download>Résumé <Download size={17}/></a></div></div>
    <div className="system-art" aria-hidden="true"><div className="art-top"><span>FROM IDEA TO IMPLEMENTATION</span><span>↗</span></div><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="core">rm<span>.</span></div><div className="node node-a"><Code2 size={18}/> build</div><div className="node node-b"><Database size={18}/> scale</div><div className="node node-c"><BrainCircuit size={18}/> learn</div><div className="art-bottom"><i/> CONNECTING THE PIECES</div></div></div>
    <div className="hero-footer"><span>JAVA & SPRING BOOT</span><span>CLOUD-NATIVE SYSTEMS</span><span>APPLIED MACHINE LEARNING</span><a href="#projects">SCROLL TO EXPLORE ↓</a></div>
   </section>
   <section id="projects" className="wrap section"><div className="section-heading"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Ideas, engineered.</h2></div><p>From full-stack applications to<br/>data-driven predictions.</p></div><div className="project-grid">{projects.map(p=><article className="project" key={p.n}><div className={'project-art project-art-'+p.n} aria-hidden="true"><p.icon size={48} strokeWidth={1}/><span>{p.n}</span><div className="art-lines"/></div><div className="project-body"><p className="eyebrow">{p.type}</p><h3>{p.title}</h3><p>{p.description}</p><ul>{p.points.map(t=><li key={t}>{t}</li>)}</ul><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div></section>
   <section id="experience" className="wrap section"><div className="section-heading"><div><p className="eyebrow">02 / EXPERIENCE</p><h2>Learning. Building. Contributing.</h2></div></div><div className="experience-row"><div className="company"><span className="company-mark">NAU</span><div><h3>Northern Arizona University</h3><p>Flagstaff, Arizona</p></div></div><div><p className="date">JAN 2025 — MAY 2025</p><h3>Teaching Assistant, Secure Design</h3><p>Supported teaching in secure coding, threat modeling, and cryptographic protocols. Guided students through assignments and one-on-one office hours, and provided feedback on core security principles.</p></div></div><div className="experience-row"><div className="company"><span className="company-mark">K</span><div><h3>KPMG</h3><p>Arogya Sri Health Care Project</p></div></div><div><p className="date">AUG 2022 — JUN 2023</p><h3>Analyst · Java Full Stack Developer</h3><p>Contributed to an Andhra Pradesh government healthcare project. Developed web interfaces, built RESTful APIs with Java and Spring Boot, and helped manage MySQL databases for large-scale health data.</p></div></div></section>
   <section id="about" className="about-band"><div className="wrap section about-grid"><div><p className="eyebrow">03 / A LITTLE ABOUT ME</p><h2>Curiosity is<br/>part of the stack.</h2><p className="about-copy">My work spans backend engineering, cloud infrastructure, and machine learning. I enjoy connecting these disciplines to build applications that are useful, secure, and ready to scale.</p><p className="about-copy">I earned my master’s in Computer Science at Northern Arizona University, where I also helped students develop a foundation in secure software design.</p><a className="text-link" href="/raditya-madina-resume.pdf" download>Get the full résumé <ArrowUpRight size={18}/></a></div><div className="education"><p className="eyebrow"><GraduationCap size={18}/> EDUCATION</p><article><span>2025</span><h3>MS in Computer Science</h3><p>Northern Arizona University</p><strong>GPA 3.8 / 4.0</strong></article><article><span>2023</span><h3>Bachelor of Technology</h3><p>Koneru Lakshmaiah Education Foundation</p><strong>GPA 9.2 / 10</strong></article></div></div></section>
   <section id="skills" className="wrap section"><div className="section-heading"><div><p className="eyebrow">04 / TOOLKIT</p><h2>The tools behind the work.</h2></div></div><div className="skills-grid">{skills.map(([name,...items])=><div key={name}><h3>{name}</h3><div className="skill-list">{items.map(t=><span key={t}>{t}</span>)}</div></div>)}</div><div className="credentials"><p className="eyebrow">CERTIFICATIONS</p><p>Microsoft Azure Fundamentals <span>·</span> Azure Developer Associate <span>·</span> Azure AI Fundamentals <span>·</span> Aviatrix Multicloud Network Associate</p></div></section>
   <section className="wrap research"><div><p className="eyebrow">RESEARCH / PERSONALIZED LEARNING</p><h3>E-learning Recommendation Architecture</h3><p>Applied decision tree algorithms to classify student data and recommend personalized courses, incorporating multiple data sources to align recommendations with learner preferences.</p></div><a className="button secondary" href="https://ieeexplore.ieee.org/document/10083579" target="_blank" rel="noreferrer">View publication <ArrowUpRight size={17}/></a></section>
   <section id="contact" className="wrap contact"><p className="eyebrow">05 / GET IN TOUCH</p><h2>Let’s build<br/><span>something that matters.</span></h2><a className="contact-email" href="mailto:raditya216@gmail.com">raditya216@gmail.com <ArrowUpRight/></a><p>Have a project or an opportunity in mind? I’d love to hear about it.</p></section>
  </main><footer className="wrap footer"><a className="wordmark" href="#home">rm<span>.</span></a><p>© {new Date().getFullYear()} Madina Jyothi Raditya Reddy</p><a href="#home">Back to top ↑</a></footer>
 </>;
}
